version: "3.8"

services:
  tg_video:
    container_name: tg_video
    build: .
    command: /bin/bash -c "alembic upgrade head && python main.py"
    restart: always
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      PHONE_NUMBER: ${PHONE_NUMBER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - .:/var/bot/
    depends_on:
      - tg_video_db
    networks:
      - tg_video_network
    env_file:
      - .env

  tg_video_db:
    image: postgres
    container_name: tg_video_db
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - tg_video_db

networks:
  tg_video_network:
    name: tg_video_network
