version: "3.8"

services:
  tg_bot_craft:
    build: .
    command: /bin/bash -c "alembic upgrade head && python main.py"
    restart: always
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    volumes:
      - ./tg_video:/tg_video/tg_video_volumes
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env

volumes:
  db:
