"""add audio

Revision ID: 6c380e952454
Revises: 88c7862d2ecc
Create Date: 2024-03-14 03:58:44.729878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c380e952454'
down_revision: Union[str, None] = '88c7862d2ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('audio_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('command')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio')
    # ### end Alembic commands ###
