"""add video_table

Revision ID: 88c7862d2ecc
Revises:
Create Date: 2024-03-13 22:23:45.085678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c7862d2ecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('command')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
